services:
  db:
    container_name: mongo-biblioteca
    image: mongo
    networks:
      - nt
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bibilioteca
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    container_name: FAST-API
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: ./app/.env
    volumes:
      - ./:/code
    depends_on:
      - db
    ports:
      - "80:8000"
    networks:
      - nt


networks:
  nt:

volumes:
  mongo-data:
